/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gPv2Eip1271Sol from "./GPv2EIP1271.sol";
export type { gPv2Eip1271Sol };
export type { IERC20 } from "./IERC20";
