/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface CowswapOrderApproverInterface extends utils.Interface {
  functions: {
    "approveOrder(address,address,uint256,uint256,uint32,uint256,bytes32,bool,bytes32,bytes32)": FunctionFragment;
    "signing()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "approveOrder" | "signing"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approveOrder",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "signing", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "approveOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signing", data: BytesLike): Result;

  events: {};
}

export interface CowswapOrderApprover extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CowswapOrderApproverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approveOrder(
      sellToken: PromiseOrValue<string>,
      buyToken: PromiseOrValue<string>,
      sellAmount: PromiseOrValue<BigNumberish>,
      buyAmount: PromiseOrValue<BigNumberish>,
      validTo: PromiseOrValue<BigNumberish>,
      feeAmountBP: PromiseOrValue<BigNumberish>,
      kind: PromiseOrValue<BytesLike>,
      partiallyFillable: PromiseOrValue<boolean>,
      sellTokenBalance: PromiseOrValue<BytesLike>,
      buyTokenBalance: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    signing(overrides?: CallOverrides): Promise<[string]>;
  };

  approveOrder(
    sellToken: PromiseOrValue<string>,
    buyToken: PromiseOrValue<string>,
    sellAmount: PromiseOrValue<BigNumberish>,
    buyAmount: PromiseOrValue<BigNumberish>,
    validTo: PromiseOrValue<BigNumberish>,
    feeAmountBP: PromiseOrValue<BigNumberish>,
    kind: PromiseOrValue<BytesLike>,
    partiallyFillable: PromiseOrValue<boolean>,
    sellTokenBalance: PromiseOrValue<BytesLike>,
    buyTokenBalance: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  signing(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    approveOrder(
      sellToken: PromiseOrValue<string>,
      buyToken: PromiseOrValue<string>,
      sellAmount: PromiseOrValue<BigNumberish>,
      buyAmount: PromiseOrValue<BigNumberish>,
      validTo: PromiseOrValue<BigNumberish>,
      feeAmountBP: PromiseOrValue<BigNumberish>,
      kind: PromiseOrValue<BytesLike>,
      partiallyFillable: PromiseOrValue<boolean>,
      sellTokenBalance: PromiseOrValue<BytesLike>,
      buyTokenBalance: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    signing(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    approveOrder(
      sellToken: PromiseOrValue<string>,
      buyToken: PromiseOrValue<string>,
      sellAmount: PromiseOrValue<BigNumberish>,
      buyAmount: PromiseOrValue<BigNumberish>,
      validTo: PromiseOrValue<BigNumberish>,
      feeAmountBP: PromiseOrValue<BigNumberish>,
      kind: PromiseOrValue<BytesLike>,
      partiallyFillable: PromiseOrValue<boolean>,
      sellTokenBalance: PromiseOrValue<BytesLike>,
      buyTokenBalance: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    signing(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    approveOrder(
      sellToken: PromiseOrValue<string>,
      buyToken: PromiseOrValue<string>,
      sellAmount: PromiseOrValue<BigNumberish>,
      buyAmount: PromiseOrValue<BigNumberish>,
      validTo: PromiseOrValue<BigNumberish>,
      feeAmountBP: PromiseOrValue<BigNumberish>,
      kind: PromiseOrValue<BytesLike>,
      partiallyFillable: PromiseOrValue<boolean>,
      sellTokenBalance: PromiseOrValue<BytesLike>,
      buyTokenBalance: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    signing(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
