/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "EIP1271Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP1271Verifier__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "GPv2Signing",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GPv2Signing__factory>;
    getContractFactory(
      name: "CowswapOrderApprover",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CowswapOrderApprover__factory>;

    getContractAt(
      name: "EIP1271Verifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP1271Verifier>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "GPv2Signing",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GPv2Signing>;
    getContractAt(
      name: "CowswapOrderApprover",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CowswapOrderApprover>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
