/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as orderApproverSol from "./OrderApprover.sol";
export type { orderApproverSol };
import type * as cowProtocol from "./cowProtocol";
export type { cowProtocol };
export * as factories from "./factories";
export type { EIP1271Verifier } from "./cowProtocol/interfaces/GPv2EIP1271.sol/EIP1271Verifier";
export { EIP1271Verifier__factory } from "./factories/cowProtocol/interfaces/GPv2EIP1271.sol/EIP1271Verifier__factory";
export type { IERC20 } from "./cowProtocol/interfaces/IERC20";
export { IERC20__factory } from "./factories/cowProtocol/interfaces/IERC20__factory";
export type { GPv2Signing } from "./cowProtocol/mixins/GPv2Signing";
export { GPv2Signing__factory } from "./factories/cowProtocol/mixins/GPv2Signing__factory";
export type { CowswapOrderApprover } from "./OrderApprover.sol/CowswapOrderApprover";
export { CowswapOrderApprover__factory } from "./factories/OrderApprover.sol/CowswapOrderApprover__factory";
